import { createRouter,createWebHistory } from "vue-router"

const router = createRouter({
    routes:[
        {
        name:'login',
        path:'/',
        'component':()=>import('../pages/login.vue')
        },
        {
            name:'知识图谱',
            path:'/knowledge',
            'component':()=>import('../pages/KnowledgeGraph.vue')
        },
        {
            name:'register',
            path:'/register',
            'component':()=>import('../pages/register.vue')
        },
        {
            name:'reset-password',
            path:'/reset-password',
            'component':()=>import('../pages/reset-password.vue')
        },
        {
            name:'reseach',
            path:'/reseach',
            'component':()=>import('../pages/reseach.vue')
        },
        {
            name:'AI-response',
            path:'/AI-response',
            'component':()=>import('../pages/AI-response.vue')
        },
        {
            name:'person',
            path:'/person',
            'component':()=>import('../pages/person.vue')
        },
        {
            name:'HTML',
            path:'/Document/HTML',
            'component':()=>import('../pages/Document/HTML.vue')
        },
        {
            name:'CSS',
            path:'/Document/CSS',
            'component':()=>import('../pages/Document/CSS.vue')
        },
        {
            name:'JavaScript',
            path:'/Document/JavaScript',
            'component':()=>import('../pages/Document/JavaScript.vue')
        },
        {
            name:'Pinia',
            path:'/Document/pinia',
            'component':()=>import('../pages/Document/Pinia.vue')
        },
        {
            name:'Vuex',
            path:'/Document/Vuex',
            'component':()=>import('../pages/Document/Vuex.vue')
        },
        {
            name:'Node.js',
            path:'/Document/Node.js',
            'component':()=>import('../pages/Document/Node.js.vue')
        },
        {
            name:'NPM',
            path:'/Document/NPM',
            'component':()=>import('../pages/Document/NPM.vue')
        },
        {
            name:'PNPM',
            path:'/Document/PNPM',
            'component':()=>import('../pages/Document/PNPM.vue')
        },
        {
            name:'Babel',
            path:'/Document/Babel',
            'component':()=>import('../pages/Document/Babel.vue')
        },
        {
            name:'ESLint',
            path:'/Document/ESLint',
            'component':()=>import('../pages/Document/ESLint.vue')
        },
        {
            name:'DOM',
            path:'/Document/DOM',
            'component':()=>import('../pages/Document/DOM.vue')
        },
        {
            name:'BOM',
            path:'/Document/BOM',
            'component':()=>import('../pages/Document/BOM.vue')
        },
        {
            name:'BrowserAPI',
            path:'/Document/BrowserAPI',
            'component':()=>import('../pages/Document/BrowserAPI.vue')
        },
        {
            name:'JSON',
            path:'/Document/JSON',
            'component':()=>import('../pages/Document/JSON.vue')
        },
        {
            name:'HTTP',
            path:'/Document/HTTP',
            'component':()=>import('../pages/Document/HTTP.vue')
        },
        {
            name:'TypeScript',
            path:'/Document/TypeScript',
            'component':()=>import('../pages/Document/TypeScript.vue')
        },
        {
            name:'ECMAScript',
            path:'/Document/ECMAScript',
            'component':()=>import('../pages/Document/ECMAScript.vue')
        },
        {
            name:'ES6+',
            path:'/Document/ES6+',
            'component':()=>import('../pages/Document/ES6+.vue')
        },
        {
            name:'ES5',
            path:'/Document/ES5',
            'component':()=>import('../pages/Document/ES5.vue')
        },
        {
            name:'Axios',
            path:'/Document/Axios',
            'component':()=>import('../pages/Document/Axios.vue')
        },
        {
            name:'FetchAPI',
            path:'/Document/FetchAPI',
            'component':()=>import('../pages/Document/FetchAPI.vue')
        },
        {
            name:'CommonJS',
            path:'/Document/CommonJS',
            'component':()=>import('../pages/Document/CommonJS.vue')
        },
        {
            name:'AMD',
            path:'/Document/AMD',
            'component':()=>import('../pages/Document/AMD.vue')
        },
        {
            name:'ESModule',
            path:'/Document/ESModule',
            'component':()=>import('../pages/Document/ESModule.vue')
        },
        {
            name:'TailwindCSS',
            path:'/Document/TailwindCSS',
            'component':()=>import('../pages/Document/TailwindCSS.vue')
        },
        {
            name:'Bootstrap',
            path:'/Document/Bootstrap',
            'component':()=>import('../pages/Document/Bootstrap.vue')
        },
        {
            name:'Sass/SCSS',
            path:'/Document/Sass/SCSS',
            'component':()=>import('../pages/Document/Sass/SCSS.vue')
        },
        {
            name:'Less',
            path:'/Document/Less',
            'component':()=>import('../pages/Document/Less.vue')
        },
        {
            name:'Stylus',
            path:'/Document/Stylus',
            'component':()=>import('../pages/Document/Stylus.vue')
        },
        {
            name:'AntDesign',
            path:'/Document/AntDesign',
            'component':()=>import('../pages/Document/AntDesign.vue')
        },
        {
            name:'ElementPlus',
            path:'/Document/ElementPlus',
            'component':()=>import('../pages/Document/ElementPlus.vue')
        },
        {
            name:'Vue项目',
            path:'/Document/Vue%E9%A1%B9%E7%9B%AE',
            'component':()=>import('../pages/Document/Vue项目.vue')
        },
        {
            name:'React项目',
            path:'/Document/React%E9%A1%B9%E7%9B%AE',
            'component':()=>import('../pages/Document/React项目.vue')
        },
        {
            name:'JS模块化',
            path:'/Document/JS%E6%A8%A1%E5%9D%97%E5%8C%96',
            'component':()=>import('../pages/Document/JS模块化.vue')
        },
        {
            name:'数据交换',
            path:'/Document/%E6%95%B0%E6%8D%AE%E4%BA%A4%E6%8D%A2',
            'component':()=>import('../pages/Document/数据交换.vue')
        },
        {
            name:'页面交互',
            path:'/Document/%E9%A1%B5%E9%9D%A2%E4%BA%A4%E4%BA%92',
            'component':()=>import('../pages/Document/页面交互.vue')
        },
        {
            name:'页面结构',
            path:'/Document/%E9%A1%B5%E9%9D%A2%E7%BB%93%E6%9E%84',
            'component':()=>import('../pages/Document/页面结构.vue')
        },
        {
            name:'网络通信',
            path:'/Document/%E7%BD%91%E7%BB%9C%E9%80%9A%E4%BF%A1',
            'component':()=>import('../pages/Document/网络通信.vue')
        },
        {
            name:'页面样式',
            path:'/Document/%E9%A1%B5%E9%9D%A2%E6%A0%B7%E5%BC%8F',
            'component':()=>import('../pages/Document/页面样式.vue')
        },
        {
            name:'Vuetify',
            path:'/Document/Vuetify',
            'component':()=>import('../pages/Document/Vuetify.vue')
        },
        {
            name:'Yarn',
            path:'/Document/Yarn',
            'component':()=>import('../pages/Document/Yarn.vue')
        },
        {
            name:'Vue2',
            path:'/Document/Vue2',
            'component':()=>import('../pages/Document/Vue2.vue')
        },
        {
            name:'Vue3',
            path:'/Document/Vue3',
            'component':()=>import('../pages/Document/Vue3.vue')
        },
        {
            name:'React',
            path:'/Document/React',
            'component':()=>import('../pages/Document/React.vue')
        },
        {
            name:'jQuery',
            path:'/Document/jQuery',
            'component':()=>import('../pages/Document/jQuery.vue')
        },
        {
            name:'Redux',
            path:'/Document/Redux',
            'component':()=>import('../pages/Document/Redux.vue')
        },
        {
            name:'ReduxToolkit',
            path:'/Document/ReduxToolkit',
            'component':()=>import('../pages/Document/ReduxToolkit.vue')
        },
        {
            name:'Vite',
            path:'/Document/Vite',
            'component':()=>import('../pages/Document/Vite.vue')
        },
        {
            name:'Webpack',
            path:'/Document/Webpack',
            'component':()=>import('../pages/Document/Webpack.vue')
        },
        {
            name:'VueRouter',
            path:'/Document/VueRouter',
            'component':()=>import('../pages/Document/VueRouter.vue')
        },
        {
            name:'ReactRouter',
            path:'/Document/ReactRouter',
            'component':()=>import('../pages/Document/ReactRouter.vue')
        },
        {
            name:'仪表盘',
            path:'/admin/home',
            'component':()=>import('../admin/home.vue')
        },
        {
            name:'UserManage',
            path:'/admin/users',
            'component':()=>import('../admin/UserManage.vue')
        },
        {
            name:'graph-display',
            path:'/admin/graph/display',
            'component':()=>import('../admin/GraphDisplay.vue')
        },
        {
            name:'nodemanager',
            path:'/admin/graph/nodes', 
            'component':()=>import('../admin/NodeManage.vue')
        },
        {
            name:'relationsmanager',
            path:'/admin/graph/relations', 
            'component':()=>import('../admin/RelationManagement.vue')
        },
        {
            name:'datastatis',
            path:'/admin/stats', 
            'component':()=>import('../admin/DataStatistics.vue')
        },
        {
            name:'logs',
            path:'/admin/logs', 
            'component':()=>import('../admin/loges.vue')
        }
    ],
    history:createWebHistory()
})

export default router